# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-29 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_id_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xschools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xschool_id', models.TextField(blank=True, default='default_id', null=True)),
                ('xschool_client', models.TextField(blank=True, default='default_client', null=True)),
            ],
        ),
    ]
