# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-08 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_id_login', '0002_xschools'),
    ]

    operations = [
        migrations.AddField(
            model_name='xschools',
            name='return_uri',
            field=models.TextField(blank=True, default='default_uri', null=True),
        ),
    ]
