# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-08 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_id_login', '0003_xschools_return_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='xschools',
            name='xschool_secret',
            field=models.TextField(blank=True, default='default_secret', null=True),
        ),
        migrations.AddField(
            model_name='xsuser',
            name='ask_oid_link',
            field=models.TextField(blank=True, default='default', null=True),
        ),
        migrations.AddField(
            model_name='xsuser',
            name='oid_linked',
            field=models.TextField(blank=True, default='default', null=True),
        ),
    ]
